project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!cours/geonum/archives/"

website:
  title: ""
  favicon: static/logo.png
  
  search: false
  
  navbar:
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Cours"
        menu:
          - text: "GeoNum"
            file: cours/geonum/01_cours_introduction.qmd
  
  sidebar:
    - title: "GeoNum"
      style: "docked"
      contents: 
        - cours/geonum/01_cours_introduction.qmd
        - cours/geonum/02_cours_architecture_client_serveur.qmd
        - cours/geonum/03_cours_geoserver.qmd
        - cours/geonum/04_cours_intro_openlayers.qmd
        - cours/geonum/05_cours_openlayers_bases.qmd
        - cours/geonum/06_cours_ajout_couches.qmd
        - cours/geonum/07_cours_interactions.qmd
        - cours/geonum/08_cours_enrichir_ma_carte.qmd
  
  page-footer: 
    left: ""
    right: ""
    center:
      - icon: github
        href: https://github.com/GradelerM
      - icon: linkedin
        href: https://fr.linkedin.com/in/marie-gradeler

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

